name: Slack Notification for Specific PR

on:
  pull_request:
    types:
      - opened

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR author and notify Slack
        if: github.event.pull_request.user.login == 'Konflux Internal p02'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "📢 *Pull Request Opened by Konflux Internal p02!*\n*Title:* $PR_TITLE\n*URL:* <$PR_URL>"
          }' \
          $SLACK_WEBHOOK_URL
