name: Slack Notification for Specific PR

on:
  pull_request:
    types:
      - opened

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Log PR Details
        run: |
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"

      - name: Debug and Notify Slack
        if: ${{ github.event.pull_request.user.login == 'Konflux Internal p02' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "Sending Slack notification..."
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"📢 *Pull Request Opened by Konflux Internal p02!*\n*Title:* $PR_TITLE\n*URL:* <$PR_URL>\"
          }" \
          $SLACK_WEBHOOK_URL
